# Generated by Django 4.2.16 on 2024-12-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom de famille')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('lang', models.CharField(default='fr', max_length=10, verbose_name='Langue de préférence')),
            ],
            options={
                'verbose_name': 'Compte utilisateur',
                'verbose_name_plural': 'Comptes utilisateurs',
            },
        ),
    ]
