# Generated by Django 4.2.16 on 2024-12-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authenticated',
            field=models.BooleanField(default=False, verbose_name='Authentifié'),
        ),
    ]
