# Generated by Django 4.2.16 on 2025-01-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='authenticated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
    ]
