# Generated by Django 4.2.16 on 2025-01-07 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Formulaire', 'verbose_name_plural': 'Formulaires'},
        ),
        migrations.RemoveField(
            model_name='form',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='author',
            field=models.IntegerField(blank=True, help_text="Identifiant de l'auteur du formulaire.", null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création du formulaire.'),
        ),
        migrations.AddField(
            model_name='form',
            name='data',
            field=models.TextField(default={}, help_text='Données des réponses du formulaire.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='id_client',
            field=models.IntegerField(default=0, help_text="Identifiant unique dans l'application."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Indique si le formulaire a été complété.'),
        ),
        migrations.AddField(
            model_name='form',
            name='model',
            field=models.IntegerField(default=0, help_text='Identifiant du modèle suivi par le formulaire.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Date de réception par le serveur.', null=django.utils.timezone.now),
            preserve_default=django.utils.timezone.now,
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ImageBlob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_blob', models.BinaryField(help_text="Données binaires de l'image.")),
                ('file_name', models.CharField(help_text="Nom du fichier d'image.", max_length=255)),
                ('content_type', models.CharField(help_text="Type MIME de l'image (ex : image/png).", max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Date de création de l'image.")),
                ('form', models.ForeignKey(help_text="Formulaire associé à l'image.", on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forms.form')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
